### PR TITLE
Implement EventsByTagQuery in PersistenceTestKitReadJournal

### PR DESCRIPTION
**Pull request by ptrdom**
Resolves https://github.com/apache/pekko/issues/1527.

### CODE REVIEW

**Comment by ptrdom** [comment]
Seeing complication errors on 2.12, will fix.

**Comment by ptrdom** [comment]
Aha, so tests have to compile on 2.12 too, will fix.

**Comment by ptrdom** [comment]
@pjfanning Seems like the only issue is with timeouts in link validator, IIUC it is a temporary failure. Is the PR otherwise fine?

**Comment by pjfanning** [comment]
Don't worry about the Link Validator. The changes look ok to me. I would like to let other people review this before it gets merged. I think this is safe for the v1.1.3 release but I want to get other opinions.

**Comment by pjfanning** [comment]
@ptrdom would you consider filling in a CLA?

https://www.apache.org/licenses/contributor-agreements.html

**Comment by pjfanning** [comment]
> Sure, cannot see a reason not to file.

Thanks @ptrdom

**Comment by ptrdom** [comment]
@pjfanning I got a message that my ICLA has been filed in the Apache Software Foundation records and that I need to contact a project to progress my application. And that I should let the project know about my preferred Apache ID, which is the same as my GitHub username - `ptrdom`. This is assuming your message counted as an invitation to be a committer.

**Comment by pjfanning** [comment]
> @pjfanning I got a message that my ICLA has been filed in the Apache Software Foundation records and that I need to contact a project to progress my application. And that I should let the project know about my preferred Apache ID, which is the same as my GitHub username - `ptrdom`. This is assuming your message counted as an invitation to be a committer.

Thanks for filling in the iCLA. In theory, the ASF requires them for significant code changes. They are also required for new committers, etc. I haven't received any notification from the ASF Secretary. This usually happens when the iCLA email includes the ASF project name. I can look it up myself but I need the full email address that you used to send the iCLA. The tool that I have access to only supports lookups with the full email address.

**Comment by pjfanning** [comment]
@ptrdom I found your iCLA in the ASF foundation svn repo so that is enough to proceed.

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
