### PR TITLE
chore: Fix scala constructor finding tests for scala 3.

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Fix https://github.com/apache/pekko/issues/1082

### CODE REVIEW

**Comment by He-Pin** [comment]
Scala 3 encoding different vs Scala 2, updating :(

**Comment by pjfanning** [comment]
unfortunately our PR build does not test this code - so let's get it merged to main when it is ready but then we run the nightly build

We can backport when we know that the main branch nightly tests pass.

**Comment by He-Pin** [comment]
@pjfanning The constructor encoding is different in Scala 3 and Scala 2, so I just move these classes to an object , and let them then closing over nothing.

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
