### PR TITLE
Avoid unnecessary shard updates while shutting down

### PR DESCRIPTION
**Pull request by nvollmar**
Refs #1341

### CODE REVIEW

**Comment by pjfanning** [comment]
looks sensible to me - let's see what other reviewers say

When we get a fix in, we might want to backport it to 1.0.x. I think we should make a 1.0.3 release in the next few weeks.

**Comment by nvollmar** [comment]
Would be good to have that in 1.0.3

**Review by samueleresca — APPROVED** [review]
looks good to me.

**Review by He-Pin — APPROVED** [review]
lgtm

**Review by Roiocam — APPROVED** [review]
LGTM, Thanks.

`ShardUpdate` will only notify Shard to start detecting the passivation. This is seems like a harmless change.

**Pull request merged**
