### PR TITLE
remove incubator notice

### PR DESCRIPTION
**Pull request by pjfanning**
appears in web site footers

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
@mdedetrich I gave up on this because I could not get it to work for persistence-cassandra module.

**Comment by pjfanning** [comment]
@mdedetrich does this change look about right? Unfortunately, I don't have to test this on my laptop this afternoon.

**Comment by pjfanning** [comment]
I ran this locally and it seems to work.

**Pull request merged**
