### PR TITLE
Update scala-steward.yml with 1.0.x branches

### PR DESCRIPTION
**Pull request by He-Pin**
Motivation:
Add 1.0.x to scala steward for auto-update deps.

### CODE REVIEW

**Comment by pjfanning** [comment]
I don't think we need this. I think we should only upgrade dependencies in 1.0.x when there are serious issues. For instance, I would have voted against the Scala upgrades merged today.

**Review by pjfanning — CHANGES_REQUESTED** [review]
One of the major points of the 1.0.0 release cycle was not to upgrade dependencies in 1.0.0 unless they were important. I think we will need a Pekko team vote on this and I will vote -1.

**Comment by He-Pin** [comment]
We can pin some dependencies on 1.0.x too.

**Comment by pjfanning** [comment]
> We can pin some dependencies on 1.0.x too.

As I said above, this needs a vote.

**Pull request closed without merging**
