### PR TITLE
perf: Reduce loops in when clean queue in BroadcastHub (#1628)

### PR DESCRIPTION
**Pull request by He-Pin**
(cherry picked from commit 9596ea4c1827701ab7f540897bba9f6209ceef15)

### CODE REVIEW

**Comment by pjfanning** [comment]
I don't think we should backport this. It is not semver friendly to be putting so many changes in patch releases.
We are taking too many risks in the patch releases as it is.

**Comment by He-Pin** [comment]
Ok, let's only get it in the next release.

**Comment by He-Pin** [comment]
@pjfanning Btw, this is a kind of bug too, because the loop can take seconds.

**Comment by He-Pin** [comment]
Okay, let me close it, anyway ,ship it in next version will be safer.

**Pull request closed without merging**
