### PR TITLE
run `sbt doc` in nightly build for Scala 3 but with without genjavadoc

### PR DESCRIPTION
**Pull request by pjfanning**
rework for #1221

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
@He-Pin @mdedetrich this doesn't work - actually breaks the build

Unfortunately, GitHub Action stuff is a bit trial and error. I might not have time until tonight or even tomorrow to try again.

**Comment by He-Pin** [comment]
> @He-Pin @mdedetrich this doesn't work - actually breaks the build
> 
> Unfortunately, GitHub Action stuff is a bit trial and error. I might not have time until tonight or even tomorrow to try again.

Maybe github action doesn't support inline evaluation ？

**Pull request merged**
