### PR TITLE
feat: streamlined approach for Behaviors #1444

### PR DESCRIPTION
**Pull request by Roiocam**
Resolves: #1444

### CODE REVIEW

**Comment by pjfanning** [comment]
@Roiocam Is this something that could be ready in the next few days? If not, can we delay it to the 1.1.1 release?

**Comment by Roiocam** [comment]
> @Roiocam Is this something that could be ready in the next few days? If not, can we delay it to the 1.1.1 release?

It's not in that hurry to contain in release 1.1.0, but I'll try my best to delivery it.

**Review by pjfanning — COMMENTED** [review]
@Roiocam if this is ready to merge, could I ask for one extra change? Could you add `@since 1.1.0` to the scaladoc on the new methods?

**Comment by Roiocam** [comment]
> @Roiocam if this is ready to merge, could I ask for one extra change?

It is ready!

>  Could you add `@since 1.1.0` to the scaladoc on the new methods?

done. Thanks

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
@Roiocam is it ok to merge this? I'm hoping to start the release process for v1.1.0.

**Comment by Roiocam** [comment]
> @Roiocam is it ok to merge this? I'm hoping to start the release process for v1.1.0.

i am no objection to this. it's just syntax sugar.

**Pull request merged**
